src/CryptoStore/Controllers/ApiControllers/ServiceController.cs
namespace CryptoStore.Controllers.ApiControllers
{
    using CryptoStore.Services.Contracts;
    using CryptoStore.ViewModels.ApiModels.Service;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using static Infrastructure.WebConstants; 

    public class ServiceController : ApiController
    {
        private readonly IServicesService service;

        public ServiceController(IServicesService service) => this.service = service;

        [HttpGet]
        [AllowAnonymous]
        public async Task<IEnumerable<ServiceRequestModel>> Services()
            => await this.service.GetServicesAsync();

        [HttpGet]
        [Route(Id)]
        public async Task<IEnumerable<ServiceDetailsRequestModel>> Details(int id)
            => await this.service.DetailsAsync(id); 
    }
}

src/CryptoStore/Controllers/PaymentController.cs
namespace CryptoStore.Controllers
{
    using CryptoStore.Infrastructure.Extensions;
    using CryptoStore.Helpers.Messages;
    using CryptoStore.Infrastructure.Services;
    using CryptoStore.Services.Contracts;
    using CryptoStore.ViewModels.BidingViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    public class PaymentController : Controller 
    {
        private readonly IPaymentService payment;
        private readonly ICurrentUserService currentUser;
        private readonly IServicesService serviceDetails;

        public PaymentController(
            IPaymentService payment,
            ICurrentUserService currentUser,
            IServicesService serviceDetails) 
        {
            this.payment = payment;
            this.currentUser = currentUser;
            this.serviceDetails = serviceDetails; 
        }  

        [Authorize]
        [HttpGet]
        public IActionResult CheckOut()
        {
            var userObj = this.currentUser.GetUsername();

            var serviceDetails = this.serviceDetails.GetServiceDetailsForCheckOut();  

            var model = new CreatePaymentsVeiwModel
            {
                Username = userObj,
                TotalSum = serviceDetails.TotalSum,
                CryptoToken = serviceDetails.CryptoTokens,
                ServiceName = serviceDetails.ServiceName
            }; 

            return this.View(model); 
        }

        [Authorize] 
        [HttpPost]
        public async Task<IActionResult> CheckOut(CreatePaymentsVeiwModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            } 

            await this.payment.CheckOutAsync(model); 

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Your payment is succesfull.Please check your email for the service you paid for!"
            }); 

            return RedirectToAction("Index", "Home"); 
        }
    } 

}

src/CryptoStore/Controllers/ServiceController.cs
namespace CryptoStore.Controllers
{
    using CryptoStore.Infrastructure.Extensions;
    using CryptoStore.Helpers.Messages;
    using CryptoStore.Services.Contracts;
    using CryptoStore.ViewModels.BidingViewModels;
    using CryptoStore.ViewModels.ServiceVeiwModel.Edit;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    using static Infrastructure.WebConstants;

    public class ServiceController : Controller
    {
        private readonly IServicesService service;

        public ServiceController(IServicesService service) => this.service = service;

        [Authorize(Roles = Admin)] 
        [Authorize(Policy = WritePolicy)]
        [HttpGet]
        public IActionResult Create() => this.View(); 

        [Authorize(Roles = Admin)] 
        [Authorize(Policy = WritePolicy)] 
        [HttpPost]
        public async Task<IActionResult> Create(CreateServiceViewModel model)   
        {
            if (!ModelState.IsValid)
            {
                return this.View(); 
            }

            await this.service.CreateAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "The service was created successfully" 
            });

            return RedirectToAction("GetAllServices", "Service");  
        } 

        public IActionResult GetAllServices()
        {  
            var model = this.service.GetAllServices();
            return this.View(model); 
        } 

        [Authorize] 
        public async Task<IActionResult> ServiceDetails(int id)
        {
            var model = await this.service.ServiceDetailsAsync(id); 
            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet]  
        public async Task<IActionResult> Edit(int id)
        {
            var model = await this.service.PrepareForEditingAsync(id);
            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpPost]
        public async Task<IActionResult> Edit(EditingViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(); 
            } 

            await this.service.EditAsync(model); 

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Succesfull editing!" 
            });

            return RedirectToAction("GetAllServices", "Service"); 
        } 

        public async Task<IActionResult> Remove(int id)
        {
            await this.service.RemoveAsync(id);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "The service is deleted!" 
            });

            return RedirectToAction("GetAllServices");
        }
    }
}

src/CryptoStore/Views/Service/Create.cshtml
@model CryptoStore.ViewModels.BidingViewModels.CreateServiceViewModel 

@{
    ViewData["Title"] = "Add Service"; 
}
<br />
<br />
<h1><b>@ViewData["Title"]</b></h1> 

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ServiceName" class="control-label"></label>
                <input asp-for="ServiceName" class="form-control" />
                <span asp-validation-for="ServiceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceImage" class="control-label"></label>
                <input asp-for="ServiceImage" class="form-control" />
                <span asp-validation-for="ServiceImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceVideo" class="control-label"></label>
                <input asp-for="ServiceVideo" class="form-control" />
                <span asp-validation-for="ServiceVideo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceDescription" class="control-label"></label>
                <input asp-for="ServiceDescription" class="form-control" />
                <span asp-validation-for="ServiceDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceExplain" class="control-label"></label>
                <input asp-for="ServiceExplain" class="form-control" />
                <span asp-validation-for="ServiceExplain" class="text-danger"></span>
            </div> 
            <div class="form-group">
                <label asp-for="Token" class="control-label"></label>
                <input asp-for="Token" class="form-control" />
                <span asp-validation-for="Token" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalSum" class="control-label"></label>
                <input asp-for="TotalSum" class="form-control" />
                <span asp-validation-for="TotalSum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/CryptoStore/Views/Service/Edit.cshtml
@model CryptoStore.ViewModels.ServiceVeiwModel.Edit.EditingViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1><b>Edit</b></h1> 

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ServiceName" class="control-label"></label>
                <input asp-for="ServiceName" class="form-control" />
                <span asp-validation-for="ServiceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceDescription" class="control-label"></label>
                <input asp-for="ServiceDescription" class="form-control" />
                <span asp-validation-for="ServiceDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceExplain" class="control-label"></label>
                <input asp-for="ServiceExplain" class="form-control" />
                <span asp-validation-for="ServiceExplain" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceImage" class="control-label"></label>
                <input asp-for="ServiceImage" class="form-control" />
                <span asp-validation-for="ServiceImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceVideo" class="control-label"></label>
                <input asp-for="ServiceVideo" class="form-control" />
                <span asp-validation-for="ServiceVideo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Token" class="control-label"></label>
                <input asp-for="Token" class="form-control" />
                <span asp-validation-for="Token" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalSum" class="control-label"></label>
                <input asp-for="TotalSum" class="form-control" />
                <span asp-validation-for="TotalSum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/CryptoStore/Views/Service/GetAllServices.cshtml
@model IEnumerable<CryptoStore.ViewModels.ServiceVeiwModel.IndexServiceViewModel>

@{
    ViewData["Title"] = "GetAllServices";
}

<head>
    <style>
        .card {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            max-width: 300px;
            margin: auto;
            text-align: center;
            font-family: arial;
        }
        .card h1 {
            background-color:grey;
        } 
        .card p {
            background-color: grey;
        }

        .card button {
            border: none;
            outline: 0;
            padding: 12px;
            color: white;
            background-color: #000;
            text-align: center;
            cursor: pointer;
            width: 100%;
            font-size: 18px;
        }

            .card button:hover {
                opacity: 0.7;
            }
        .header {
            padding: 100px;
            font-size: 100px;
            text-align: center;
            background-image: url("https://cdn.shopify.com/s/files/1/1737/1965/products/image_8_1024x1024.png?v=1509864203");
            height: 50%;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            position: relative;
        }
    </style>
</head>
<div class="header">

</div>
<body>
    <h2 style="text-align:center"><b>Services</b></h2>
    <br />
    <div class="container"> 
        <div class="row justify-content-between">
            @foreach (var service in Model)
            {
                <div class="col-md-4">
                    <div class="card">
                        <img src="@service.ServiceImage" style="width:100%">
                        <h1>@service.ServiceName</h1>
                        <p>@service.Description</p>
                        <a asp-route-id="@service.Id" asp-controller="Service" asp-action="ServiceDetails">
                            <p><button>Get Now</button></p>
                        </a>
                    </div>
                </div>
            }
        </div>
    </div>
</body>

src/CryptoStore/Views/Service/ServiceDetails.cshtml
@model IEnumerable<CryptoStore.ViewModels.ServiceVeiwModel.ServiceDetailsViewModel>

@{
    ViewData["Title"] = "ServiceDetails";
}
<br />
<br />
<title>CryptoFuture</title>
<style>
    body, h1, h2, h3, h4, h5 {
        font-family: "Poppins", sans-serif
    }

    body {
        font-size: 16px;
    }

    .w3-half img {
        margin-bottom: -6px;
        margin-top: 16px;
        opacity: 0.8;
        cursor: pointer
    }

        .w3-half img:hover {
            opacity: 1
        }
</style>
<body>

    <div class="w3-main" style="margin-left:340px;margin-right:40px">
        @foreach (var service in Model)
        {
            <div class="w3-container" style="margin-top:80px" id="showcase">
                <h1 class="w3-jumbo"><b>@service.Name</b></h1>
                <hr style="width:50px;border:5px solid red" class="w3-round">
            </div>
            <div class="w3-row-padding">
                <div class="w3-half">
                    <img src="@service.Image" style="width:100%">
                </div>
            </div>
            <div class="w3-container" style="margin-top:75px">
                <h1 class="w3-xxxlarge w3-text-red"><b>CryptoFuture.</b></h1>
                <hr style="width:50px;border:5px solid red" class="w3-round">
                <p>
                    <b>@service.Description</b>
                </p>
            </div>

            <div clas="container">
                <h1 class="w3-xxxlarge w3-text-red"><b>Service Package.</b></h1>
                <hr style="width:50px;border:5px solid red" class="w3-round">
            </div>
            <div class="w3-row-padding">
                <div class="w3-half">
                    <ul class="w3-ul w3-light-grey w3-center">
                        <li class="w3-red w3-xlarge w3-padding-32"><b>Each Package Has These Bonuses</b></li>
                        <li class="w3-padding-16"><b>+ Crypto education(Free)</b></li>
                        <li class="w3-padding-16"><b>+ Financialy literate(Free)</b></li>
                        <li class="w3-padding-16"><b>+ Financialy independent(Free)</b></li>
                        <li class="w3-padding-16"><b>Service:  @service.ServiceExplain</b></li>
                        <p><b>@service.TotalSum</b> <b>@service.CryptoToken</b></p>
                        <li class="w3-light-grey w3-padding-24">
                            <a asp-controller="Payment" asp-action="CheckOut" class="w3-button w3-red w3-padding-large w3-hover-black">
                                Get now
                            </a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="w3-light-grey w3-padding-24">
                                 <a asp-route-id="@service.Id" asp-controller="Service" asp-action="Edit" class="w3-button btn-group w3-red w3-padding-large w3-hover-black">Edit</a>
                                <a asp-route-id="@service.Id" asp-controller="Service" asp-action="Remove" class="w3-button btn-group w3-red w3-padding-large w3-hover-black">Remove</a> 
                            </li>
                        }
                    </ul>
                </div>
            </div>
        }
    </div>
</body>