src/CryptoStore/Controllers/AdministrationController.cs
namespace CryptoStore.Controllers 
{
    using CryptoStore.Infrastructure.Extensions;
    using CryptoStore.Helpers.Messages;
    using CryptoStore.Services.Contracts;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    using static Infrastructure.WebConstants; 

    [Authorize(Roles = Admin)]  
    [Authorize(Policy = WritePolicy)] 
    public class AdministrationController : Controller 
    {
        private readonly IAdministrationService administration;
        public AdministrationController(
            IAdministrationService administration)
            => this.administration = administration;

        [HttpGet]
        public IActionResult Create()
        {
            var model = this.administration.PrepareForCreate();

            return this.View(model); 
        } 

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model) 
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            }

            await  this.administration.CreateRoleAsync(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Succesfully added role!"
            });

            return RedirectToAction("GetAllRoles", "Administration");
        }

        public IActionResult UserWithRoles()
        {
            var model = this.administration.UserRoles(); 
            return this.View(model);
        }

        public async Task<IActionResult> Payments()
        {
            var model = await this.administration.PaymentsAsync();
            return this.View(model); 
        }
         
        public async Task<IActionResult> Ban(string id) 
        {
            await this.administration.BanAsync(id); 

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Danger,
                Message = "This account is LockOut!"
            }); 

            return RedirectToAction("UserWithRoles"); 
        }

        public async Task<IActionResult> UnBan(string id)
        {
            await this.administration.UnBanAsync(id);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success, 
                Message = "Тhis account is unlocked!"
            }); 

            return RedirectToAction("UserWithRoles");
        } 
    }
}

src/CryptoStore/Controllers/ApiControllers/PartnerController.cs
namespace CryptoStore.Controllers.ApiControllers
{
    using CryptoStore.Services.Contracts;
    using CryptoStore.ViewModels.ApiModels.Partner;
    using Microsoft.AspNetCore.Mvc;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    public class PartnerController : ApiController
    {
        private readonly IPartnerService partner;

        public PartnerController(IPartnerService partner) => this.partner = partner;

        [HttpGet]
        public async Task<IEnumerable<PartnerRequestModel>> Partners()
            => await this.partner.PartnersAsync(); 
    }
}

src/CryptoStore/Controllers/ApiControllers/ResourceController.cs
namespace CryptoStore.Controllers.ApiControllers
{
    using CryptoStore.Services.Contracts;
    using CryptoStore.ViewModels.ApiModels.Resource;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    public class ResourceController :ApiController
    {
        private readonly IResourcesService resource;

        public ResourceController(IResourcesService resource) => this.resource = resource;

        [HttpGet]
        [AllowAnonymous]
        public async Task<IEnumerable<ResourceRequestModel>> Resources()
            => await this.resource.GetResourcesAsync(); 
    }
}

src/CryptoStore/Controllers/ApiControllers/ServiceController.cs
namespace CryptoStore.Controllers.ApiControllers
{
    using CryptoStore.Services.Contracts;
    using CryptoStore.ViewModels.ApiModels.Service;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using static Infrastructure.WebConstants; 

    public class ServiceController : ApiController
    {
        private readonly IServicesService service;

        public ServiceController(IServicesService service) => this.service = service;

        [HttpGet]
        [AllowAnonymous]
        public async Task<IEnumerable<ServiceRequestModel>> Services()
            => await this.service.GetServicesAsync();

        [HttpGet]
        [Route(Id)]
        public async Task<IEnumerable<ServiceDetailsRequestModel>> Details(int id)
            => await this.service.DetailsAsync(id); 
    }
}

src/CryptoStore/Controllers/NewsletterController.cs
namespace CryptoStore.Controllers
{
    using CryptoStore.Infrastructure.Extensions;
    using CryptoStore.Helpers.Messages;
    using CryptoStore.Services.Contracts;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;
    using CryptoStore.ViewModels.BidingViewModels;

    using static Infrastructure.WebConstants;

    public class NewsletterController : Controller
    {
        private readonly INewsletterService newsletter;

        public NewsletterController(INewsletterService newsletter) => this.newsletter = newsletter;

        [Authorize] 
        [HttpGet] 
        public IActionResult AddUserForNewsletter() => this.View();

        [Authorize]
        [HttpPost] 
        public async Task<IActionResult> AddUserForNewsletter(AddUserForNewsletterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(); 
            }

            await this.newsletter.AddAsync(model);  

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "You subscribre for us!"
            }); 
             
            return RedirectToAction("Index", "Home"); 
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        public IActionResult GetAllNewsletters()  
        {
            var model = this.newsletter.AllNewsletters(); 

            return this.View(model); 
        }
    }
}

src/CryptoStore/Controllers/PaymentController.cs
namespace CryptoStore.Controllers
{
    using CryptoStore.Infrastructure.Extensions;
    using CryptoStore.Helpers.Messages;
    using CryptoStore.Infrastructure.Services;
    using CryptoStore.Services.Contracts;
    using CryptoStore.ViewModels.BidingViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    public class PaymentController : Controller 
    {
        private readonly IPaymentService payment;
        private readonly ICurrentUserService currentUser;
        private readonly IServicesService serviceDetails;

        public PaymentController(
            IPaymentService payment,
            ICurrentUserService currentUser,
            IServicesService serviceDetails) 
        {
            this.payment = payment;
            this.currentUser = currentUser;
            this.serviceDetails = serviceDetails; 
        }  

        [Authorize]
        [HttpGet]
        public IActionResult CheckOut()
        {
            var userObj = this.currentUser.GetUsername();

            var serviceDetails = this.serviceDetails.GetServiceDetailsForCheckOut();  

            var model = new CreatePaymentsVeiwModel
            {
                Username = userObj,
                TotalSum = serviceDetails.TotalSum,
                CryptoToken = serviceDetails.CryptoTokens,
                ServiceName = serviceDetails.ServiceName
            }; 

            return this.View(model); 
        }

        [Authorize] 
        [HttpPost]
        public async Task<IActionResult> CheckOut(CreatePaymentsVeiwModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            } 

            await this.payment.CheckOutAsync(model); 

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Your payment is succesfull.Please check your email for the service you paid for!"
            }); 

            return RedirectToAction("Index", "Home"); 
        }
    } 

}

src/CryptoStore/Views/Administration/Create.cshtml
@model Microsoft.AspNetCore.Identity.IdentityRole

@{
    ViewData["Title"] = "Add Role";
}
<br />
<br />
<h1><b>@ViewData["Title"]</b></h1>  
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div> 
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}  

src/CryptoStore/Views/Administration/Payments.cshtml
@model IEnumerable<CryptoStore.ViewModels.AdministrationViewModel.AllPaymentsVeiwModel>

@{
    ViewData["Title"] = "Payments";
}
<br /> 
<br />
<head>
    <style>
        * {
            box-sizing: border-box;
        }

        #myTable {
            border-collapse: collapse;
            width: 100%;
            border: 1px solid #ddd;
            font-size: 18px;
        }

            #myTable th, #myTable td {
                text-align: left;
                padding: 12px;
            }

            #myTable tr {
                border-bottom: 1px solid #ddd;
            }

                #myTable tr.header, #myTable tr:hover {
                    background-color: black;
                }

        input[type=text] {
            width: 130px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            background-color: white;
            background-image: url('searchicon.png');
            background-position: 10px 10px;
            background-repeat: no-repeat;
            padding: 12px 20px 12px 40px;
            -webkit-transition: width 0.4s ease-in-out;
            transition: width 0.4s ease-in-out;
        }

            input[type=text]:focus {
                width: 100%;
            }
    </style>
</head>
<body>

    <h2><b>Payments</b></h2> 
    <form>
        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for usernames..." title="Type in a name">
    </form>
    <table id="myTable">
        <tr class="header">
            <th style="width:60%;">Username</th>
            <th style="width:40%;">Email</th>
            <th style="width:40%;">Phone</th>
            <th style="width:40%;">Service</th>
            <th style="width:40%;">Token</th> 
            <th style="width:40%;">Sum</th>
        </tr>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Username</td>
                <td>@user.Email</td>
                <td>@user.Phone</td>
                <td>@user.ServiceName</td> 
                <td>@user.CryptoToken</td> 
                <td>@user.TotalSum</td> 
            </tr>

        }
    </table>

    <script>
        function myFunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>

</body>

src/CryptoStore/Views/Administration/UserWithRoles.cshtml
@model IEnumerable<CryptoStore.ViewModels.AdministrationViewModel.UserRolesViewModel>

@{
    ViewData["Title"] = "UserWithRoles";
} 
<br />
<br />
    <a asp-controller="Newsletter" asp-action="GetAllNewsletters" class="btn btn-group btn-success">Subscribers</a>
    <a asp-controller="Administration" asp-action="Payments" class="btn btn-group btn-success">Payments</a> 
    <a asp-controller="Administration" asp-action="Create" class="btn btn-group btn-success">Add Role</a> 
    <a asp-controller="Service" asp-action="Create" class="btn btn-group btn-success">Add Service</a>
    <a asp-controller="Resource" asp-action="Create" class="btn btn-group btn-success">Add Resource</a> 
    <a asp-controller="Partner" asp-action="Add" class="btn btn-group btn-success">Add Partner</a>
<br />
<br />

<head>
    <style>
        * {
            box-sizing: border-box;
        }

        #myTable {
            border-collapse: collapse;
            width: 100%;
            border: 1px solid #ddd;
            font-size: 18px;
        }

            #myTable th, #myTable td {
                text-align: left;
                padding: 12px;
            }

            #myTable tr {
                border-bottom: 1px solid #ddd;
            }

                #myTable tr.header, #myTable tr:hover {
                    background-color: black;
                }

        input[type=text] {
            width: 130px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            background-color: white;
            background-image: url('searchicon.png');
            background-position: 10px 10px;
            background-repeat: no-repeat;
            padding: 12px 20px 12px 40px;
            -webkit-transition: width 0.4s ease-in-out;
            transition: width 0.4s ease-in-out;
        }

            input[type=text]:focus {
                width: 100%;
            }
    </style>
</head>
<body>

    <h2><b>Users</b></h2>
    <form>
        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for usernames..." title="Type in a name">
    </form>
    <table id="myTable">
        <tr class="header">
            <th style="width:60%;">Username</th>
            <th style="width:40%;">Email</th>
            <th style="width:40%;">Email Confirmed</th>
            <th style="width:40%;">Role</th>
            <th style="width:40%;">Locked</th>
            <th style="width:40%;">Ban</th>
            <th style="width:40%;">UnBan</th> 
        </tr>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Username</td>
                <td>@user.Email</td>
                <td>@user.EmailConfirmed</td>
                <td>@user.RoleName</td> 
                <td>@user.IsLocked</td> 
                <td><a asp-route-id="@user.Id" asp-controller="Administration" asp-action="Ban" class="btn btn-danger" role="button">Ban</a></td> 
                 <td><a asp-route-id="@user.Id" asp-controller="Administration" asp-action="UnBan" class="btn btn-danger" role="button">UnBan</a></td> 
            </tr>

        }
    </table>

    <script>
        function myFunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>

</body> 