src/CryptoStore/Controllers/ApiControllers/PartnerController.cs
namespace CryptoStore.Controllers.ApiControllers
{
    using CryptoStore.Services.Contracts;
    using CryptoStore.ViewModels.ApiModels.Partner;
    using Microsoft.AspNetCore.Mvc;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    public class PartnerController : ApiController
    {
        private readonly IPartnerService partner;

        public PartnerController(IPartnerService partner) => this.partner = partner;

        [HttpGet]
        public async Task<IEnumerable<PartnerRequestModel>> Partners()
            => await this.partner.PartnersAsync(); 
    }
}

src/CryptoStore/Controllers/ApiControllers/ServiceController.cs
namespace CryptoStore.Controllers.ApiControllers
{
    using CryptoStore.Services.Contracts;
    using CryptoStore.ViewModels.ApiModels.Service;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using static Infrastructure.WebConstants; 

    public class ServiceController : ApiController
    {
        private readonly IServicesService service;

        public ServiceController(IServicesService service) => this.service = service;

        [HttpGet]
        [AllowAnonymous]
        public async Task<IEnumerable<ServiceRequestModel>> Services()
            => await this.service.GetServicesAsync();

        [HttpGet]
        [Route(Id)]
        public async Task<IEnumerable<ServiceDetailsRequestModel>> Details(int id)
            => await this.service.DetailsAsync(id); 
    }
}

src/CryptoStore/Controllers/MessageNotificationController.cs
namespace CryptoStore.Controllers
{
    using CryptoStore.Infrastructure.Extensions;
    using CryptoStore.Helpers.Messages;
    using CryptoStore.Infrastructure.Services;
    using CryptoStore.Services.Contracts;
    using CryptoStore.ViewModels.BidingViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    using static Infrastructure.WebConstants;

    public class MessageNotificationController : Controller
    {
        private readonly IMessageNotificationService messageNotification;
        private readonly ICurrentUserService currentUser;  

        public MessageNotificationController(
            IMessageNotificationService messageNotification,
            ICurrentUserService currentUser)
        {
            this.messageNotification = messageNotification;
            this.currentUser = currentUser;
        }

        [Authorize] 
        [HttpGet]
        public IActionResult Create()
        {
            var username = this.currentUser.GetUsername();

            var model = new CreateMessageViewModel
            {
                Username = username,           
            };

            return this.View(model); 
        }

        [Authorize]
        [HttpPost] 
        public async Task<IActionResult> Create(CreateMessageViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View();
            }

            await this.messageNotification.CreateMessageAsyc(model);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Your message was sent successfully. We will contact you!"
            }); 

            return RedirectToAction("Index", "Home"); 
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        public IActionResult Notifications()
        {
            var model = this.messageNotification.Notification();

            return this.View(model); 
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        public async Task<IActionResult> DetailsNotification(int id)
        {
            var model = await this.messageNotification.DetailsAsync(id);

            return this.View(model);
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        [HttpGet(Id)] 
        public async Task<IActionResult> Clear(int id) 
        {
            await this.messageNotification.ClearAsync(id);

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Succesfull!" 
            });

            return RedirectToAction("Notifications"); 
        }
    }
}

src/CryptoStore/Controllers/NewsletterController.cs
namespace CryptoStore.Controllers
{
    using CryptoStore.Infrastructure.Extensions;
    using CryptoStore.Helpers.Messages;
    using CryptoStore.Services.Contracts;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;
    using CryptoStore.ViewModels.BidingViewModels;

    using static Infrastructure.WebConstants;

    public class NewsletterController : Controller
    {
        private readonly INewsletterService newsletter;

        public NewsletterController(INewsletterService newsletter) => this.newsletter = newsletter;

        [Authorize] 
        [HttpGet] 
        public IActionResult AddUserForNewsletter() => this.View();

        [Authorize]
        [HttpPost] 
        public async Task<IActionResult> AddUserForNewsletter(AddUserForNewsletterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(); 
            }

            await this.newsletter.AddAsync(model);  

            this.TempData.Put("__Message", new MessageModel()
            {
                Type = MessageType.Success,
                Message = "You subscribre for us!"
            }); 
             
            return RedirectToAction("Index", "Home"); 
        }

        [Authorize(Roles = Admin)]
        [Authorize(Policy = WritePolicy)]
        public IActionResult GetAllNewsletters()  
        {
            var model = this.newsletter.AllNewsletters(); 

            return this.View(model); 
        }
    }
}

src/CryptoStore/Views/Shared/_Layout.cshtml
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - CryptoFuture</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">
</head>

<style>
    body, h1, h2, h3, h4, h5, h6 {
        font-family: "Montserrat", sans-serif
    }

    .w3-row-padding img {
        margin-bottom: 12px
    }
    /* Set the width of the sidebar to 120px */
    .w3-sidebar {
        width: 120px;
        background: #222;
    }
    /* Add a left margin to the "page content" that matches the width of the sidebar (120px) */
    #main {
        margin-left: 120px
    }
    /* Remove margins from "page content" on small screens */
    @@media only screen and (max-width: 600px) {
        #main {
            margin-left: 0
        }
    }

    body {
        font-family: 'Signika', sans-serif;
    }

    .bg-grey {
        background: #292929;
    }

    .logo-footer {
        margin-bottom: 40px;
    }

    footer {
        color: grey;
    }

        footer p, a {
            font-size: 12px;
            font-family: 'Roboto', sans-serif;
        }

        footer h6 {
            font-family: 'Playfair Display', serif;
            margin-bottom: 40px;
            position: relative;
        }

            footer h6:after {
                position: absolute;
                content: "";
                background: grey;
                width: 12%;
                height: 1px;
                left: 0;
                bottom: -20px;
            }

    .btn-footer {
        color: grey;
        text-decoration: none;
        border: 1px solid;
        border-radius: 43px;
        font-size: 13px;
        padding: 7px 30px;
        line-height: 47px;
    }

        .btn-footer:hover {
            text-decoration: none;
        }

    .form-footer input[type="text"] {
        border: none;
        border-radius: 16px 0 0 16px;
        outline: none;
        padding-left: 10px;
    }

    ::placeholder {
        font-size: 10px;
        padding-left: 10px;
        font-style: italic;
    }

    .form-footer input[type="button"] {
        border: none;
        background: #232323;
        margin-left: -5px;
        color: #fff;
        outline: none;
        border-radius: 0 16px 16px 0;
        padding: 2px 12px;
    }

    .social .fa {
        color: grey;
        font-size: 22px;
        padding: 10px 15px;
        background: #3c3c3c;
    }

    footer ul li {
        list-style: none;
        display: block;
    }

    footer ul {
        padding-left: 0;
    }

        footer ul li a {
            text-decoration: none;
            color: grey;
            text-decoration: none;
        }

    a:hover {
        text-decoration: none;
        color: #f5f5f5 !important;
    }

    .logo-part {
        border-right: 1px solid grey;
        height: 100%;
    }
</style>
<body class="w3-black">
    <header>
        <!-- Icon Bar (Sidebar - hidden on small screens) -->
        <nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center">
            <!-- Avatar image in top left corner -->
            <img src="https://scontent.fsof10-1.fna.fbcdn.net/v/t1.15752-9/239999231_1143935682763925_2531683563105675287_n.png?_nc_cat=101&ccb=1-5&_nc_sid=ae9488&_nc_ohc=D7ePzHBaLvgAX8ahQQn&_nc_ht=scontent.fsof10-1.fna&oh=14d92e43066975d621ac927954923380&oe=61460927" style="width:100%">
            <a asp-controller="Home" asp-action="Index" class="w3-bar-item w3-button w3-padding-large w3-black">
                <i class="fa fa-home w3-xxlarge"></i>
                <p>HOME</p>
            </a>
            @if (User.IsInRole("Admin"))
            {
                <a asp-controller="MessageNotification" asp-action="Notifications" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
                    <i class="fa fa-fw fa-envelope w3-xxlarge"></i>
                    <p>Notifications</p>
                </a>
            }
            <a asp-controller="Resource" asp-action="Index" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
                <i class="fa fa-fw fa-btc w3-xxlarge"></i>
                <p>Resource</p>
            </a>
            <a asp-controller="Service" asp-action="GetAllServices" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
                <i class="fa fa-star w3-xxlarge"></i>
                <p>Services</p>
            </a>
            <a asp-controller="Newsletter" asp-action="AddUserForNewsletter" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
                <i class="fa fa-plus w3-xxlarge"></i>
                <p>Newsletter</p>
            </a>

             @if (User.IsInRole("Admin"))
             {
                    <a asp-controller="Administration" asp-action="UserWithRoles" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
                         <i class="fa fa-cogs w3-xxlarge"></i>
                         <p>Administration</p>
                     </a>
             }

            <partial name="_LoginPartial" />
        </nav>

        <!-- Navbar on small screens (Hidden on medium and large screens) -->
        <div class="w3-top w3-hide-large w3-hide-medium" id="myNavbar">
            <div class="w3-bar w3-black w3-opacity w3-hover-opacity-off w3-center w3-small">
                <a asp-controller="Home" asp-action="Index" class="w3-bar-item w3-button" style="width:25% !important">HOME</a>
                <a asp-controller="MessageNotification" asp-action="Notifications" class="w3-bar-item w3-button" style="width:25% !important">Notifications</a>
                <a asp-controller="Resource" asp-action="Index" class="w3-bar-item w3-button" style="width:25% !important">Resource</a>
                <a asp-controller="Service" asp-action="GetAllServices" class="w3-bar-item w3-button" style="width:25% !important">Service</a>
                <a asp-controller="Newsletter" asp-action="AdduserForNewsletter" class="w3-bar-item w3-button" style="width:25% !important">Administration</a>
                <a asp-controller="Administration" asp-action="GetAllRoles" class="w3-bar-item w3-button" style="width:25% !important">Administration</a>
                <partial name="_LoginPartial" />
            </div>

        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_MessagePartial" />
            @RenderBody()
        </main>
    </div>
    <div class="w3-padding-large" id="main">
        <footer class="container-fluid bg-grey py-5">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-6 ">
                                <div class="logo-part">
                                    <strong class="w-50">CryptoFuture</strong>
                                    <br />
                                    <br />
                                    @*<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1lvDf_zlAtG5SsyaA2aFnybKzdU3dW4yECOmTlysomxxwOdqDudhA2R3sTzYlG1Vgxi4&usqp=CAU" class="w-50 logo-footer">*@
                                    <p><b>Be financially literate and independent!</b></p>
                                    <p><b>Contacts</b></p>
                                    <p><b><a href="tel:0893690274"><i class="fa fa-fw fa-phone"></i>0893690274</a></b></p>
                                    <p><b><a href="mailto:cryptoofuture@gmail.com"><i class="fa fa-fw fa-envelope"></i>cryptoofuture@@gmail.com</a></b></p>
                                </div>
                            </div>
                            <div class="col-md-6 px-4">
                                <h6>About</h6>
                                <a asp-controller="Home" asp-action="About" class="btn-footer">CryptoFuture</a><br>
                                <a asp-controller="MessageNotification" asp-action="Create" class="btn-footer">Contact Us</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-6 px-4">
                                <h6>Intelligence</h6>
                                <div class="row ">
                                    <div class="col-md-6">
                                        <ul>
                                            <li><b><a asp-controller="Service" asp-action="GetAllServices">Businnes Intelligence</a></b></li>
                                            <br />
                                            <li><b><a asp-controller="Resource" asp-action="Index">Bitcoin Education</a></b></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-6 px-4">
                                        <ul>
                                            <li><b><a asp-controller="Home" asp-action="Privacy">Privacy</a></b></li>
                                            <br />
                                            <li><b><a asp-controller="Partner" asp-action="GetPartnes"> Partnes</a></b></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 ">
                                <h6>We accept</h6>
                                <p><b><i class="fa fa-fw fa-btc"></i>Bitcoin</b></p>
                                <p><b><i class="fa fa-fw fa-credit-card"></i>Credit Card</b></p>
                                <div class="social">
                                    <a href="https://github.com/Ivailo369369"><i class="fa fa-github" aria-hidden="true"></i></a>
                                    <a href="https://www.instagram.com/cryptoofuture/?hl=bg"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </div> 
</body>
</html>

src/CryptoStore/Views/Shared/_MessagePartial.cshtml
@using CryptoStore.Infrastructure.Extensions 

@if (TempData.ContainsKey("__Message"))
{
    var message = TempData.Get<MessageModel>("__Message"); 
    <message type="@message.Type" message="@message.Message"></message>     
} 